services:
  u2bot:
    build: .
    restart: unless-stopped
    mem_limit: 128m
    memswap_limit: 128m
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
    volumes:
      - ./config.json:/app/config.json:ro
      - ./watchers.json:/app/watchers.json
