#!/usr/bin/env bash
#
# harden-server.sh — One-shot hardening for a fresh Ubuntu 22.04/24.04 Linode.
# Run as root. Interactive where it needs input, automated everywhere else.
#
set -euo pipefail

# ─── Colors / helpers ─────────────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { printf "${GREEN}[INFO]${NC}  %s\n" "$*"; }
warn()  { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
error() { printf "${RED}[ERROR]${NC} %s\n" "$*" >&2; }
fatal() { error "$@"; exit 1; }

# ─── 1. Preflight checks ─────────────────────────────────────────────────────

[[ $EUID -eq 0 ]] || fatal "This script must be run as root."

if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    [[ "$ID" == "ubuntu" ]] || fatal "This script targets Ubuntu. Detected: $ID"
    info "Detected $PRETTY_NAME"
else
    fatal "/etc/os-release not found — cannot confirm Ubuntu."
fi

echo ""
warn "This script will harden this server. Changes include:"
echo "  - Creating a non-root deploy user"
echo "  - Disabling root SSH login and password auth"
echo "  - Enabling UFW firewall (SSH only)"
echo "  - Installing fail2ban"
echo "  - Enabling automatic security updates"
echo "  - Applying kernel/network sysctl tweaks"
echo ""
read -rp "Proceed? [y/N] " confirm
[[ "$confirm" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }

# ─── 2. System update ────────────────────────────────────────────────────────

info "Updating package lists and upgrading installed packages..."
apt update
apt upgrade -y

info "Installing essentials..."
apt install -y ufw fail2ban unattended-upgrades

# ─── 3. Create non-root deploy user ──────────────────────────────────────────

read -rp "Username for the deploy user [deploy]: " DEPLOY_USER
DEPLOY_USER="${DEPLOY_USER:-deploy}"

if id "$DEPLOY_USER" &>/dev/null; then
    info "User '$DEPLOY_USER' already exists — skipping creation."
else
    info "Creating user '$DEPLOY_USER'..."
    adduser --disabled-password --gecos "" "$DEPLOY_USER"
fi

usermod -aG sudo "$DEPLOY_USER"

# Let the deploy user sudo without a password (they have no password anyway)
echo "$DEPLOY_USER ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/$DEPLOY_USER"
chmod 440 "/etc/sudoers.d/$DEPLOY_USER"

# Copy SSH authorized_keys from root
DEPLOY_HOME=$(eval echo "~$DEPLOY_USER")
DEPLOY_SSH_DIR="$DEPLOY_HOME/.ssh"
mkdir -p "$DEPLOY_SSH_DIR"

if [[ -f /root/.ssh/authorized_keys ]]; then
    cp /root/.ssh/authorized_keys "$DEPLOY_SSH_DIR/authorized_keys"
    info "Copied root's authorized_keys to $DEPLOY_USER."
else
    warn "No /root/.ssh/authorized_keys found."
    echo "Paste the public SSH key for $DEPLOY_USER (one line):"
    read -r SSH_KEY
    echo "$SSH_KEY" > "$DEPLOY_SSH_DIR/authorized_keys"
fi

chown -R "$DEPLOY_USER:$DEPLOY_USER" "$DEPLOY_SSH_DIR"
chmod 700 "$DEPLOY_SSH_DIR"
chmod 600 "$DEPLOY_SSH_DIR/authorized_keys"

# Verify sudo works for the new user
if sudo -u "$DEPLOY_USER" sudo -n true 2>/dev/null; then
    info "Verified: '$DEPLOY_USER' can sudo."
else
    fatal "'$DEPLOY_USER' cannot sudo — aborting before SSH lockout."
fi

# ─── 4. SSH hardening ────────────────────────────────────────────────────────

info "Hardening SSH configuration..."
cat > /etc/ssh/sshd_config.d/hardening.conf <<EOF
# Server hardening — generated by harden-server.sh
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
X11Forwarding no
MaxAuthTries 3
AllowUsers $DEPLOY_USER
EOF

# Ensure privilege separation directory exists (missing on some fresh installs)
mkdir -p /run/sshd

# Validate config before restarting
sshd -t || fatal "sshd config test failed — not restarting. Fix /etc/ssh/sshd_config.d/hardening.conf manually."
systemctl restart sshd
info "sshd restarted with hardened config."

# ─── 5. Firewall (UFW) ───────────────────────────────────────────────────────

info "Configuring UFW firewall..."
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw --force enable
info "UFW enabled — only SSH (port 22) is open."

# ─── 6. Fail2ban ─────────────────────────────────────────────────────────────

info "Configuring fail2ban..."
cat > /etc/fail2ban/jail.local <<'EOF'
[DEFAULT]
bantime  = 600
findtime = 600
maxretry = 5

[sshd]
enabled = true
port    = ssh
filter  = sshd
logpath = /var/log/auth.log
EOF

systemctl enable fail2ban
systemctl restart fail2ban
info "fail2ban enabled with SSH jail (5 retries, 10-min ban)."

# ─── 7. Automatic security updates ───────────────────────────────────────────

info "Enabling unattended security upgrades..."
cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

cat > /etc/apt/apt.conf.d/50unattended-upgrades <<'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot "false";
EOF

info "Unattended-upgrades configured for security patches."

# ─── 8. Kernel / network hardening (sysctl) ──────────────────────────────────

echo ""
read -rp "Disable IPv6? [y/N] " disable_ipv6

info "Applying sysctl network hardening..."
cat > /etc/sysctl.d/99-hardening.conf <<EOF
# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Don't send ICMP redirects
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Disable source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# SYN flood protection
net.ipv4.tcp_syncookies = 1

# Log martian packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1
EOF

if [[ "$disable_ipv6" =~ ^[Yy]$ ]]; then
    cat >> /etc/sysctl.d/99-hardening.conf <<'EOF'

# Disable IPv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF
    info "IPv6 will be disabled."
fi

sysctl --system
info "sysctl hardening applied."

# ─── 9. Misc ─────────────────────────────────────────────────────────────────

read -rp "Timezone [UTC]: " TZ_CHOICE
TZ_CHOICE="${TZ_CHOICE:-UTC}"
timedatectl set-timezone "$TZ_CHOICE"
info "Timezone set to $TZ_CHOICE."

if dpkg -l snapd &>/dev/null 2>&1; then
    read -rp "Remove snapd? [Y/n] " remove_snap
    remove_snap="${remove_snap:-Y}"
    if [[ "$remove_snap" =~ ^[Yy]$ ]]; then
        apt purge -y snapd
        info "snapd removed."
    fi
fi

# ─── 10. Summary ─────────────────────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
info "Server hardening complete. Here's what was done:"
echo ""
echo "  [+] System packages updated"
echo "  [+] User '$DEPLOY_USER' created with sudo + SSH key"
echo "  [+] SSH: root login disabled, password auth disabled"
echo "  [+] SSH: only '$DEPLOY_USER' may log in"
echo "  [+] UFW firewall enabled (SSH only)"
echo "  [+] fail2ban enabled (SSH jail, 5 retries / 10-min ban)"
echo "  [+] Automatic security updates enabled"
echo "  [+] Kernel/network sysctl hardening applied"
echo "  [+] Timezone set to $TZ_CHOICE"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
warn "IMPORTANT — do NOT close this session yet!"
echo ""
echo "  1. Open a NEW terminal"
echo "  2. SSH in as the deploy user:  ssh $DEPLOY_USER@<this-ip>"
echo "  3. Verify you can run:         sudo whoami"
echo "  4. Only then close this root session"
echo ""
echo "  If you lock yourself out, use the Linode console (Lish) to recover."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
